# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-15T22:14:20+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    error: str = Field(..., description="Error code, e.g. `not_found: id 42`.")


class PingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: str = Field(..., examples=["ok"])
    ready: bool
    openapiVersion: str = Field(..., description="Spec version the server speaks.")


class SettlementName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str


class StatusResult(BaseModel):
    """
    Generic mutation acknowledgement.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class PopulationItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    district: str
    adults: int = Field(..., ge=0)
    children: int = Field(..., ge=0)
    bots: int = Field(..., ge=0)


class PopulationCounts(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    adults: int = Field(..., ge=0)
    children: int = Field(..., ge=0)
    bots: int = Field(..., ge=0)


class GoodStock(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    available: int
    all: int


class DistrictResources(RootModel[dict[str, GoodStock]]):
    """
    Map of good name → stock counts.
    """

    root: dict[str, GoodStock]


class Resources(RootModel[dict[str, DistrictResources]]):
    """
    Map of district name → DistrictResources.
    """

    root: dict[str, DistrictResources]


class Time(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    dayNumber: int = Field(..., ge=0)
    dayProgress: float = Field(..., ge=0.0, le=1.0)
    partialDayNumber: float = Field(..., ge=0.0)


class Weather(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    cycle: int = Field(..., ge=0)
    cycleDay: int = Field(..., ge=0)
    cycleLengthInDays: int = Field(..., ge=1)
    isHazardous: bool
    temperateWeatherDuration: int = Field(..., ge=0)
    hazardousWeatherDuration: int = Field(..., ge=0)


class WorkHours(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endHours: float = Field(..., ge=0.0)
    areWorkingHours: bool


class Speed1(IntEnum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class Speed(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    speed: Speed1


class Crops(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    growing: int | None = Field(default=None, ge=0)
    ready: int | None = Field(default=None, ge=0)
    species: list[str] | None = None


class Speed2(IntEnum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class SummaryTime(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    dayNumber: int | None = Field(default=None, ge=0)
    dayProgress: float | None = Field(default=None, ge=0.0, le=1.0)
    partialDayNumber: float | None = Field(default=None, ge=0.0)
    speed: Speed2 | None = None


class SummaryWeather(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    cycle: int | None = Field(default=None, ge=0)
    cycleDay: int | None = Field(default=None, ge=0)
    cycleLengthInDays: int | None = Field(default=None, ge=1)
    isHazardous: bool | None = None
    temperateWeatherDuration: int | None = Field(default=None, ge=0)
    hazardousWeatherDuration: int | None = Field(default=None, ge=0)


class Housing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    occupiedBeds: int | None = Field(default=None, ge=0)
    totalBeds: int | None = Field(default=None, ge=0)
    homeless: int | None = Field(default=None, ge=0)


class Employment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    assigned: int | None = Field(default=None, ge=0)
    vacancies: int | None = Field(default=None, ge=0)
    unemployed: int | None = Field(default=None, ge=0)


class Wellbeing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    average: float | None = None
    critical: int | None = Field(default=None, ge=0)
    miserable: int | None = Field(default=None, ge=0)


class Dc(BaseModel):
    """
    District Center location/orientation.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    x: int | None = None
    y: int | None = None
    z: int | None = None
    entranceX: int | None = None
    entranceY: int | None = None
    orientation: str | None = None


class SummaryDistrict(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    population: PopulationCounts
    resources: dict[str, int] | None = Field(
        default=None,
        description="Map of good → stock count (summary aggregate, simpler than /api/resources).",
    )
    housing: Housing | None = None
    employment: Employment | None = None
    wellbeing: Wellbeing | None = None
    dc: Dc | None = Field(
        default=None, description="District Center location/orientation."
    )


class District(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    population: PopulationCounts
    resources: DistrictResources | None = None


class ImportOption(Enum):
    Forced = "Forced"
    Auto = "Auto"
    None_ = "None"


class GoodDistribution(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    good: str
    importOption: ImportOption
    exportThreshold: float


class Unlocked(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Unlockable(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    cost: int = Field(..., ge=0)
    unlocked: Unlocked


class WellbeingNeed(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    favorableWellbeing: float
    unfavorableWellbeing: float


class Notification(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    subject: str = Field(
        ..., description="Localization key or notification identifier."
    )
    description: str
    cycle: int = Field(..., ge=0)
    cycleDay: int = Field(..., ge=0)
    entityId: int | None = Field(
        default=None,
        description="Building/beaver entity this notification refers to, when applicable.",
    )


class Alert(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str = Field(
        ...,
        description="Alert category (e.g. unstaffed, unpowered, unreachable, status).",
    )
    id: int = Field(..., description="Building entity ID raising the alert.")
    name: str
    workers: str | None = Field(
        default=None,
        description="Optional context (e.g. assigned/desired counts for staffing alerts).",
    )


class PrefabCost(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    good: str
    amount: int = Field(..., ge=0)


class IsGenerator(IntEnum):
    integer_0 = 0
    integer_1 = 1


class PowerBuilding(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    name: str
    isGenerator: IsGenerator
    nominalInput: float
    nominalOutput: float


class MapSize(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    x: int = Field(..., ge=1)
    y: int = Field(..., ge=1)
    z: int = Field(..., ge=1)


class Tiles(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mapSize: MapSize
    tiles: list[dict[str, Any]] | None = Field(
        default=None,
        description="Per-tile data for the requested rectangle (when bounds are provided).",
    )


class Cluster(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    x: int
    y: int
    z: int
    total: int = Field(..., ge=0)
    grown: int = Field(..., ge=0)
    species: dict[str, int] = Field(..., description="Map of species name → count.")


class Events(Enum):
    """
    Event names subscribed to, or the literal "all".
    """

    all = "all"


class Webhook(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    Id: str = Field(
        ..., description="Webhook ID (returned to clients as `id` on register)."
    )
    Url: AnyUrl
    events: list[str] | Events = Field(
        ..., description='Event names subscribed to, or the literal "all".'
    )
    disabled: bool
    failures: int = Field(..., ge=0)


class WebhookList(RootModel[list[Webhook]]):
    root: list[Webhook]


class PaginatedEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total: int = Field(..., ge=0)
    offset: int = Field(..., ge=0)
    limit: int = Field(..., ge=0)
    items: list[dict[str, Any]]


class EntityList(PaginatedEnvelope):
    """
    Deprecated alias for the paginated envelope; concrete list endpoints have their own typed envelopes (BuildingList, BeaverList, TreeList, CropList, GatherableList).
    """


class Orientation(Enum):
    south = "south"
    west = "west"
    north = "north"
    east = "east"


class Finished(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Paused(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Pausable(IntEnum):
    integer_0 = 0
    integer_1 = 1


class ConstructionPriority(Enum):
    VeryLow = "VeryLow"
    Low = "Low"
    Normal = "Normal"
    High = "High"
    VeryHigh = "VeryHigh"


class WorkplacePriority(Enum):
    VeryLow = "VeryLow"
    Low = "Low"
    Normal = "Normal"
    High = "High"
    VeryHigh = "VeryHigh"


class Reachable(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Powered(IntEnum):
    integer_0 = 0
    integer_1 = 1


class IsConsumer(IntEnum):
    integer_0 = 0
    integer_1 = 1


class HasMaterials(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Floodgate(IntEnum):
    integer_0 = 0
    integer_1 = 1


class IsClutch(IntEnum):
    integer_0 = 0
    integer_1 = 1


class ClutchEngaged(IntEnum):
    integer_0 = 0
    integer_1 = 1


class ReadyToProduce(IntEnum):
    integer_0 = 0
    integer_1 = 1


class NeedsNutrients(IntEnum):
    integer_0 = 0
    integer_1 = 1


class IsWonder(IntEnum):
    integer_0 = 0
    integer_1 = 1


class WonderActive(IntEnum):
    integer_0 = 0
    integer_1 = 1


class HasAutomator(IntEnum):
    integer_0 = 0
    integer_1 = 1


class IsAutomated(IntEnum):
    integer_0 = 0
    integer_1 = 1


class IsTransmitter(IntEnum):
    integer_0 = 0
    integer_1 = 1


class BuildingAutomation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = None
    hasAutomator: HasAutomator | None = None
    automatorName: str | None = None
    isAutomated: IsAutomated | None = None
    isTransmitter: IsTransmitter | None = None
    state: str | None = None
    inputName: str | None = None
    inputs: list[dict[str, Any]] | None = None
    outputs: list[dict[str, Any]] | None = None
    config: dict[str, Any] | None = None


class IsBot(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Contaminated(IntEnum):
    integer_0 = 0
    integer_1 = 1


class HasHome(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Overburdened(IntEnum):
    integer_0 = 0
    integer_1 = 1


class AnyCritical(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Favorable(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Critical(IntEnum):
    integer_0 = 0
    integer_1 = 1


class BeaverNeed(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    group: str
    points: float = Field(
        ...,
        description="Fulfillment level; negative for unfavorable needs that drain wellbeing.",
    )
    wellbeing: int
    favorable: Favorable
    critical: Critical


class Alive(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Grown(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Marked(IntEnum):
    integer_0 = 0
    integer_1 = 1


class Plant(BaseModel):
    """
    Tree or planted crop entity (shared shape).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    name: str
    x: int
    y: int
    z: int
    alive: Alive
    grown: Grown | None = None
    growth: float | None = Field(default=None, ge=0.0, le=1.0)
    marked: Marked | None = None


class Gatherable(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    name: str
    x: int
    y: int
    z: int
    alive: Alive


class AgentStatus(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class AgentMode(Enum):
    """
    `autonomous` lets the connector decide cadence; `request` waits for
    the player to type a prompt and press Launch. Default = `request`.

    """

    autonomous = "autonomous"
    request = "request"


class PendingRequest(BaseModel):
    """
    Single-slot prompt waiting to be picked up by the connector.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int = Field(
        ...,
        description="Monotonic request id. Connectors ack with `acked_request_id` >= this value.",
        ge=1,
    )
    prompt: str


class AgentState(BaseModel):
    """
    Full widget/connector state snapshot returned by `/api/agent/state`
    and `/api/tbot/heartbeat`.

    """

    model_config = ConfigDict(
        extra="allow",
    )
    mode: AgentMode
    goal: str = Field(..., description="Free-form objective text.")
    ready: bool = Field(
        ...,
        description="Launch gate. False until the player presses Launch in the widget.",
    )
    pendingRequest: PendingRequest | None
    agentStatus: str = Field(
        ..., description="Connector-reported status string (free-form)."
    )
    lastError: str | None = Field(
        ...,
        description="Most recent fatal error reported by the connector. `null` if no error has been reported in this session.",
    )


class AgentRequestAck(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    pendingRequest: PendingRequest


class ReadyAck(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ready: bool


class TbotRegisterAck(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    registered: bool
    webhook_url: AnyUrl


class Error(Enum):
    game_not_ready = "game_not_ready"


class GameNotReady(BaseModel):
    """
    Returned with HTTP 409 from any non-whitelisted `/api/*` route while
    `ready=false`. The whitelist is `/api/agent/*`, `/api/ready`,
    `/api/tbot/*`, and `/api/ping`.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error
    hint: str


class Population(RootModel[list[PopulationItem]]):
    root: list[PopulationItem]


class Summary(BaseModel):
    """
    Aggregated snapshot: time + weather + districts + key totals.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    settlement: str
    faction: str
    science: int = Field(..., ge=0)
    alerts: dict[str, int] | None = Field(
        default=None, description="Map of alert type → count."
    )
    buildings: dict[str, int] | None = Field(
        default=None, description="Building totals grouped by category."
    )
    crops: Crops | None = None
    districts: list[SummaryDistrict]
    foodClusters: list[Cluster] | None = None
    treeClusters: list[Cluster] | None = None
    time: SummaryTime
    weather: SummaryWeather


class DistrictList(RootModel[list[District]]):
    root: list[District]


class DistrictDistribution(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    district: str
    goods: list[GoodDistribution]


class Science(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    points: int = Field(..., ge=0)
    unlockables: list[Unlockable]


class WellbeingCategory(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    group: str
    current: float
    max: float
    needs: list[WellbeingNeed]


class Notifications(RootModel[list[Notification]]):
    root: list[Notification]


class Alerts(RootModel[list[Alert]]):
    root: list[Alert]


class Prefab(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    sizeX: int = Field(..., ge=1)
    sizeY: int = Field(..., ge=1)
    sizeZ: int = Field(..., ge=1)
    scienceCost: int | None = Field(default=None, ge=0)
    unlocked: bool | None = None
    cost: list[PrefabCost] | None = None


class PowerNetwork(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    supply: float
    demand: float
    buildings: list[PowerBuilding]


class TreeClusters(RootModel[list[Cluster]]):
    root: list[Cluster]


class FoodClusters(RootModel[list[Cluster]]):
    root: list[Cluster]


class TreeList(PaginatedEnvelope):
    items: list[Plant] | None = None


class CropList(PaginatedEnvelope):
    items: list[Plant] | None = None


class GatherableList(PaginatedEnvelope):
    items: list[Gatherable] | None = None


class Building(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    name: str
    x: int
    y: int
    z: int
    orientation: Orientation
    finished: Finished
    paused: Paused
    pausable: Pausable | None = None
    constructionPriority: ConstructionPriority | None = None
    workplacePriority: WorkplacePriority | None = None
    maxWorkers: int | None = Field(default=None, ge=0)
    desiredWorkers: int | None = Field(default=None, ge=0)
    assignedWorkers: int | None = Field(default=None, ge=0)
    reachable: Reachable | None = None
    powered: Powered | None = None
    isGenerator: IsGenerator | None = None
    isConsumer: IsConsumer | None = None
    nominalPowerInput: float | None = None
    nominalPowerOutput: float | None = None
    powerDemand: float | None = None
    powerSupply: float | None = None
    buildProgress: float | None = Field(default=None, ge=0.0, le=1.0)
    materialProgress: float | None = Field(default=None, ge=0.0, le=1.0)
    hasMaterials: HasMaterials | None = None
    stock: int | None = None
    capacity: int | None = None
    storageMode: str | None = None
    allowedGood: str | None = None
    dwellers: int | None = Field(default=None, ge=0)
    maxDwellers: int | None = Field(default=None, ge=0)
    floodgate: Floodgate | None = None
    height: float | None = None
    maxHeight: float | None = None
    isClutch: IsClutch | None = None
    clutchEngaged: ClutchEngaged | None = None
    currentRecipe: str | None = None
    productionProgress: float | None = Field(default=None, ge=0.0, le=1.0)
    readyToProduce: ReadyToProduce | None = None
    needsNutrients: NeedsNutrients | None = None
    nutrients: int | None = None
    effectRadius: int | None = Field(default=None, ge=0)
    isWonder: IsWonder | None = None
    wonderActive: WonderActive | None = None
    alerts: str | None = Field(
        default=None, description="Comma-joined alert types active on this building."
    )
    inventory: dict[str, int] | None = None
    recipes: list[str] | None = None
    automation: BuildingAutomation | None = None


class Beaver(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int
    name: str
    district: str
    x: int
    y: int
    z: int
    isBot: IsBot
    contaminated: Contaminated | None = None
    deterioration: float | None = None
    hasHome: HasHome | None = None
    lifeProgress: float | None = Field(default=None, ge=0.0, le=1.0)
    liftingCapacity: int | None = Field(default=None, ge=0)
    carryAmount: int | None = Field(default=None, ge=0)
    carrying: str | None = None
    overburdened: Overburdened | None = None
    anyCritical: AnyCritical | None = None
    workplace: str | None = None
    wellbeing: int | None = None
    needs: list[BeaverNeed] | None = None


class Distribution(RootModel[list[DistrictDistribution]]):
    root: list[DistrictDistribution]


class WellbeingReport(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    beavers: int = Field(..., ge=0)
    categories: list[WellbeingCategory]


class Prefabs(RootModel[list[Prefab]]):
    root: list[Prefab]


class PowerNetworks(RootModel[list[PowerNetwork]]):
    root: list[PowerNetwork]


class BuildingList(PaginatedEnvelope):
    items: list[Building] | None = None


class BeaverList(PaginatedEnvelope):
    items: list[Beaver] | None = None
